[project]
name = "Test search operational monitoring project"
platform = "firefox_desktop"
xaxis = "submission_date"
is_rollout = false
compact_visualization = true
skip_default_metrics = true
start_date = "2023-01-01"
alerts = ["adclick_threshold"]

# need to come back to this once I know the metrics we're working with
metrics = ["main_bing_adclicks"]


[project.population]
data_source = "main"
monitor_entire_population = true
#channel = "release" # commenting this out to work around issue: https://github.com/mozilla/opmon/issues/146

[metrics.main_bing_adclicks]
data_source = "main"
select_expression = "SUM(CASE WHEN normalized_engine = \"Bing\" THEN ad_click ELSE 0 END)"

[metrics.main_bing_adclicks.statistics]
sum = {}

[data_sources]

[data_sources.main]
from_expression = "search.search_clients_engines_sources_daily"
submission_date_column = "DATE(submission_date)"

[alerts]

[alerts.adclick_threshold]
type = "threshold"
metrics = ["main_bing_adclicks"]
min = [38000]
max = [100000]
