[project]
name = "Test search operational monitoring project"
platform = "firefox_desktop"
xaxis = "submission_date"
is_rollout = false
compact_visualization = true
skip_default_metrics = true
start_date = "2023-01-01"
alerts = [
    "hist_diff"
]

# need to come back to this once I know the metrics we're working with
metrics = [
    "main_google_adclicks"
]


[project.population]
data_source = "main"
monitor_entire_population = true
channel = "release"

[metrics.main_google_adclicks]
data_source = "main"
select_expression = "SUM(CASE WHEN normalized_engine = \"Google\" THEN ad_clicks ELSE 0 END)"

[metrics.main_google_adclicks.statistics]
sum = {}

[data_sources]

[data_sources.main]
from_expression = "search.search_clients_engines_sources_daily"
submission_date_column = "DATE(submission_date)"

[alerts]

[alerts.hist_diff]
type = "avg_diff"
metrics = [
    "main_google_adclicks"
]
window_size = 7
max_relative_change = 0.25
percentiles = [25, 50, 75, 95]
